version: "3.9"
services:

  # CONFIG SERVER
  config-server:
    image: uf13/config-server:8-alpine
    build:
      context: ./confserver
    # ports:
    #   - 9999:9999
    networks:
      af:

  # EUREKA
  eureka:
    image: uf13/eureka:8-alpine
    build:
      context: ./eureka-server
    # ports: 
    #   - 8761:8761
    networks:
      af:

  # MONGO
  mongo: 
    image: mongo:4
    ports: 
      - 27017:27017
    volumes:
      - "mongodbdata:/data/db"
    networks:
      af:

  # CATALOGUE
  catalogue:
    image: uf13/catalogue:11-alpine
    build:
      context: ./catalogue
    depends_on:
      - config-server
      - mongo
    restart: on-failure
    environment:
      - MONGO_HOST=mongo
    # ports:
    #   - 7777:7777
    networks:
      af:

  # PURCHASE
  purchase:
    image: uf13/puchase:11-alpine
    build:
      context: ./purchase
    depends_on:
      - config-server
      - mongo
    restart: on-failure
    environment:
      - MONGO_HOST=mongo
    # ports:
    #   - 7788:7788
    networks:
      af:

  # GATEWAY
  gateway:
    image: uf13/gateway:11-alpine
    build:
      context: ./gateway
    depends_on:
      - config-server
      - eureka
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      af:
networks:
  af: 

volumes:
  mongodbdata:
