spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: catalogueModule
          uri: http://catalogue:7777/
          predicates:
          - Path=/api/catalogue/**
          filters:
          - StripPrefix=1

        - id: purchaseModule
          uri: http://purchase:7788
          predicates:
          - Path=/api/purchase/**
          filters:
          - StripPrefix=1

        - id: eurekaModule
          uri: https://eureka:8080/
          predicates:
          - Path=/eureka/**
          filters:
          - StripPrefix=1
     