spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: catalogueModule
          uri: lb://CATALOGUE
          predicates:
          - Path=/api/catalogue/**
          filters:
          - StripPrefix=1

        - id: purchaseModule
          uri: lb://PURCHASE
          predicates:
          - Path=/api/purchase/**
          filters:
          - StripPrefix=1

        - id: eurekaModule
          uri: lb://EUREKA
          predicates:
          - Path=/eureka/**
          filters:
          - StripPrefix=1
     