version: "3.9"
services:
  eureka:
    image: uf13/eureka:8-alpine
    build:
      context: ./eureka-server
    ports: 
      - 8761:8761
    networks:
      af: 
        aliases:
          - eureka
networks:
  af: 