{
 "title": "SpringBootApp Status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Catalogue total request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zipkin_reporter_messages_total{job=\"catalogue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalogue request by Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (zipkin_reporter_messages_total{job=\"catalogue\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pie chart",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 9, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zipkin_reporter_messages_total{job=\"catalogue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zipkin_reporter_messages_total{job=\"gateway\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zipkin_reporter_messages_total{job=\"purchase\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway total request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zipkin_reporter_messages_total{job=\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway request by Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "sum by(job) (zipkin_reporter_messages_total{job=\"gateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purchase total request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zipkin_reporter_messages_total{job=\"purchase\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purchase request by Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "sum by(job) (zipkin_reporter_messages_total{job=\"purchase\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}